# get ip from  v4_cidr_blocks = ["10.0.10.0/24"] in vm subnet, from 10.0.10.3 to 10.0.10.254 ( 0 - network adress, 1 - gateway, 2 - mb use for cloud service, 255 - broadcast address)
ha_cluster_virtual_ip: 10.0.10.200
ha_cluster_virtual_port: 7443
